Fix Release Note spacing final

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -2,7 +2,7 @@ name: Android CI
 
 on:
   push:
-    branches: [ "release-notes-formatting" ]
+    branches: [ "master" ]
 
 permissions: write-all
 
@@ -197,154 +197,154 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # aab-build:
-  #   if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
-  #   needs: setup-version
-  #   runs-on: ubuntu-latest
+  aab-build:
+    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
+    needs: setup-version
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-  #     - name: Set up JDK 17
-  #       uses: actions/setup-java@v4
-  #       with:
-  #         java-version: '17'
-  #         distribution: 'temurin'
-  #         cache: gradle
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: gradle
       
-  #     - name: Read version args
-  #       run: |
-  #         NEW_VERSION_RAW="${{ needs.setup-version.outputs.new_version_string }}"
-  #         echo -e "Raw NEW_VERSION = ${NEW_VERSION_RAW}"
-  #         NEW_VERSION="${NEW_VERSION_RAW#v}"
-  #         echo -e "Stripped NEW_VERSION = ${NEW_VERSION}"
-  #         echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+      - name: Read version args
+        run: |
+          NEW_VERSION_RAW="${{ needs.setup-version.outputs.new_version_string }}"
+          echo -e "Raw NEW_VERSION = ${NEW_VERSION_RAW}"
+          NEW_VERSION="${NEW_VERSION_RAW#v}"
+          echo -e "Stripped NEW_VERSION = ${NEW_VERSION}"
+          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
 
-  #     - name: Read release notes
-  #       run: |
-  #         RELEASE_NOTES="${{ needs.setup-version.outputs.release_notes_string }}"
-  #         echo -e "Read RELEASE_NOTES = ${RELEASE_NOTES}"
-  #         echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
+      - name: Read release notes
+        run: |
+          RELEASE_NOTES="${{ needs.setup-version.outputs.release_notes_string }}"
+          echo -e "Read RELEASE_NOTES = ${RELEASE_NOTES}"
+          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
 
-  #     - name: Process and Write Release Notes to File
-  #       run: |
-  #         # Replace literal \n with actual newline characters
-  #         echo "${{ env.RELEASE_NOTES }}" | sed 's/\\n/\n/g' > release_notes.txt
-  #         # Put release notes in a directory for upload to Google Play
-  #         mkdir -p distribution/whatsnew
-  #         cat release_notes.txt > distribution/whatsnew/whatsnew-en-CA
+      - name: Process and Write Release Notes to File
+        run: |
+          # Replace literal \n with actual newline characters
+          echo "${{ env.RELEASE_NOTES }}" | sed 's/\\n/\n/g' > release_notes.txt
+          # Put release notes in a directory for upload to Google Play
+          mkdir -p distribution/whatsnew
+          cat release_notes.txt > distribution/whatsnew/whatsnew-en-CA
 
-  #     - name: Grant execute permission for gradlew
-  #       run: chmod +x gradlew
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
-  #     - name: Set up signing keys
-  #       run: |
-  #         echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > ${{ github.workspace }}/my-release-key.jks
-  #       env:
-  #         KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
+      - name: Set up signing keys
+        run: |
+          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > ${{ github.workspace }}/my-release-key.jks
+        env:
+          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
 
-  #     - name: Increment Version Code and Set Version Name
-  #       id: increment_version
-  #       run: |
-  #         # Print initial content of the file
-  #         echo "Initial content of build.gradle.kts:"
-  #         cat app/build.gradle.kts
+      - name: Increment Version Code and Set Version Name
+        id: increment_version
+        run: |
+          # Print initial content of the file
+          echo "Initial content of build.gradle.kts:"
+          cat app/build.gradle.kts
       
-  #         # Read the current version code and name
-  #         VERSION_CODE=$(grep 'versionCode' app/build.gradle.kts | awk '{print $3}' | tr -d '[:space:]')
-  #         VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk -F'\"' '{print $2}')
+          # Read the current version code and name
+          VERSION_CODE=$(grep 'versionCode' app/build.gradle.kts | awk '{print $3}' | tr -d '[:space:]')
+          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk -F'\"' '{print $2}')
         
-  #         # Increment version code
-  #         NEW_VERSION_CODE=$((VERSION_CODE + 1))
+          # Increment version code
+          NEW_VERSION_CODE=$((VERSION_CODE + 1))
         
-  #         # Use the version name fetched from the setup-version job
-  #         NEW_VERSION_NAME="${{ env.NEW_VERSION }}"
+          # Use the version name fetched from the setup-version job
+          NEW_VERSION_NAME="${{ env.NEW_VERSION }}"
         
-  #         echo "New VERSION_CODE: $NEW_VERSION_CODE"
-  #         echo "New VERSION_NAME: $NEW_VERSION_NAME"
+          echo "New VERSION_CODE: $NEW_VERSION_CODE"
+          echo "New VERSION_NAME: $NEW_VERSION_NAME"
         
-  #         # Update the build.gradle.kts file with new values using Python
-  #         python3 -c "
-  #         import re
+          # Update the build.gradle.kts file with new values using Python
+          python3 -c "
+          import re
           
-  #         filename = 'app/build.gradle.kts'
-  #         old_version_code = '$VERSION_CODE'
-  #         new_version_code = '$NEW_VERSION_CODE'
-  #         old_version_name = '$VERSION_NAME'
-  #         new_version_name = '$NEW_VERSION_NAME'
+          filename = 'app/build.gradle.kts'
+          old_version_code = '$VERSION_CODE'
+          new_version_code = '$NEW_VERSION_CODE'
+          old_version_name = '$VERSION_NAME'
+          new_version_name = '$NEW_VERSION_NAME'
           
-  #         with open(filename, 'r') as file:
-  #             content = file.read()
+          with open(filename, 'r') as file:
+              content = file.read()
           
-  #         content = re.sub(rf'versionCode\s*=\s*{old_version_code}', f'versionCode = {new_version_code}', content)
-  #         content = re.sub(rf'versionName\s*=\s*\"{old_version_name}\"', f'versionName = \"{new_version_name}\"', content)
+          content = re.sub(rf'versionCode\s*=\s*{old_version_code}', f'versionCode = {new_version_code}', content)
+          content = re.sub(rf'versionName\s*=\s*\"{old_version_name}\"', f'versionName = \"{new_version_name}\"', content)
           
-  #         with open(filename, 'w') as file:
-  #             file.write(content)
-  #         "
+          with open(filename, 'w') as file:
+              file.write(content)
+          "
       
-  #         # Check if the file has been updated
-  #         if [ $? -ne 0 ]; then
-  #           echo "Error: Python script failed."
-  #           exit 1
-  #         else
-  #           echo "Python script succeeded."
-  #         fi
+          # Check if the file has been updated
+          if [ $? -ne 0 ]; then
+            echo "Error: Python script failed."
+            exit 1
+          else
+            echo "Python script succeeded."
+          fi
         
-  #         # Print file content after modifications
-  #         echo "Content of build.gradle.kts after modifications:"
-  #         cat app/build.gradle.kts
+          # Print file content after modifications
+          echo "Content of build.gradle.kts after modifications:"
+          cat app/build.gradle.kts
         
-  #         # Check for changes
-  #         git config --global user.email "github-actions@github.com"
-  #         git config --global user.name "GitHub Actions"
-  #         git status
+          # Check for changes
+          git config --global user.email "github-actions@github.com"
+          git config --global user.name "GitHub Actions"
+          git status
         
-  #         # Output new values for next step
-  #         echo "NEW_VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV
-  #         echo "NEW_VERSION_NAME=$NEW_VERSION_NAME" >> $GITHUB_ENV
+          # Output new values for next step
+          echo "NEW_VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV
+          echo "NEW_VERSION_NAME=$NEW_VERSION_NAME" >> $GITHUB_ENV
         
         
-  #     - name: Build AAB
-  #       run: ./gradlew bundleAab-release
-  #       env:
-  #         KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks
-  #         KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
-  #         KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
-  #         KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
+      - name: Build AAB
+        run: ./gradlew bundleAab-release
+        env:
+          KEYSTORE_FILE: ${{ github.workspace }}/my-release-key.jks
+          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
+          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
+          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
 
-  #     - name: List build output directory
-  #       run: ls -R app/build/outputs/bundle/
+      - name: List build output directory
+        run: ls -R app/build/outputs/bundle/
 
-  #     - name: Upload AAB to GitHub
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: app-aab-release.aab
-  #         path: app/build/outputs/bundle/aab-release/app-aab-release.aab
+      - name: Upload AAB to GitHub
+        uses: actions/upload-artifact@v4
+        with:
+          name: app-aab-release.aab
+          path: app/build/outputs/bundle/aab-release/app-aab-release.aab
 
-  #     - name: Commit Version Code and Name Changes
-  #       run: |
-  #         # Check if NEW_VERSION_CODE is not empty
-  #         #if [ -n "${{ env.NEW_VERSION_CODE }}" ]; then
-  #           echo "Committing new version: ${{ env.NEW_VERSION_CODE }}" 
-  #           git config --global user.email "github-actions@github.com"
-  #           git config --global user.name "GitHub Actions"
-  #           git status
-  #           git add app/build.gradle.kts
-  #           git commit -m "Increment versionCode to ${{ env.NEW_VERSION_CODE }} and versionName to ${{ env.NEW_VERSION_NAME }} [skip ci]"
-  #           git push origin ${{ github.ref_name }}
-  #         #else
-  #           #echo "No version code update required."
-  #         #fi
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Commit Version Code and Name Changes
+        run: |
+          # Check if NEW_VERSION_CODE is not empty
+          #if [ -n "${{ env.NEW_VERSION_CODE }}" ]; then
+            echo "Committing new version: ${{ env.NEW_VERSION_CODE }}" 
+            git config --global user.email "github-actions@github.com"
+            git config --global user.name "GitHub Actions"
+            git status
+            git add app/build.gradle.kts
+            git commit -m "Increment versionCode to ${{ env.NEW_VERSION_CODE }} and versionName to ${{ env.NEW_VERSION_NAME }} [skip ci]"
+            git push origin ${{ github.ref_name }}
+          #else
+            #echo "No version code update required."
+          #fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  #     - name: Upload AAB to Google Play Closed Test
-  #       uses: r0adkll/upload-google-play@v1
-  #       with:
-  #         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
-  #         packageName: com.askariya.lostcitiesscorecalculator
-  #         releaseFiles: app/build/outputs/bundle/aab-release/app-aab-release.aab
-  #         whatsNewDirectory: distribution/whatsnew
-  #         track: alpha
+      - name: Upload AAB to Google Play Closed Test
+        uses: r0adkll/upload-google-play@v1
+        with:
+          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
+          packageName: com.askariya.lostcitiesscorecalculator
+          releaseFiles: app/build/outputs/bundle/aab-release/app-aab-release.aab
+          whatsNewDirectory: distribution/whatsnew
+          track: alpha
